export default {
    EMOTIONS_LIST_REQUESTED: 'EMOTIONS_LIST_REQUESTED',
    EMOTIONS_LIST_RECEIVED: 'EMOTIONS_LIST_RECEIVED',

    EMOTIONS_RESULTS_REQUESTED: 'EMOTIONS_RESULTS_REQUESTED',
    EMOTIONS_RESULTS_RECEIVED: 'EMOTIONS_RESULTS_RECEIVED'
}